# Cloudflare Pages configuration
name = "eventureai-web"
main = ".vercel/output/static/_worker.js"
compatibility_date = "2024-03-01"
node_compat = true

[site]
bucket = ".vercel/output/static"

[vars]
NEXT_PUBLIC_ROOT_DOMAIN = "eventureai.com"
